import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
print(sns.get_dataset_names())
#df=sns.load_dataset("penguin")
df=pd.read_csv('penguin.csv')
print(df.head(10))
print(df.shape)
print(df.tail())
print(df.isnull().sum())
print(df.describe())
print(df.dtypes)
print(df.info())
print(df.describe(include='all'))
print(df.corr(numeric_only=True))
sns.heatmap(df.corr(numeric_only=True),annot=True)
plt.show()
df.select_dtypes(include=[np.number]).hist(figsize=(12,8))
df.select_dtypes(include=[np.number]).plot(kind='box',subplots=True, layout=(3,2), sharex=False, sharey=False, figsize=(8,12))
plt.show()
print(df.sex.values_counts())
df.island.value_counts()
df.species.value_counts()
sns.countplot(data=df, x="sex")
plt.show()
sns.countplot(data=df, x="island")
plt.show()
sns.countplot(data=df, x="species")
plt.show()
sns.countplot(data=df, x="sex", hue="species")
plt.show()
sns.countplot(data=df, x="island", hue="species")
plt.show()
sns.countplot(data=df, x="island", hue="sex")
plt.show()
sns.pairplot(data=df, hue="species")
plt.show()